version: "3"
services:
  ndn-node-a:
    build:
      context: .
    networks:
      - ndn-network
    volumes:
      - ./work:/work
    tty: true
  ndn-node-b:
    build:
      context: .
    networks:
      - ndn-network
    volumes:
      - ./work:/work
    tty: true
  ndn-node-c:
    build:
      context: .
    networks:
      - ndn-network
    volumes:
      - ./work:/work
    tty: true

networks:
  ndn-network:
    name: ndn-network
