apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ndn-c
spec:
  serviceName: "ndn-c-service"
  replicas: 1
  selector:
    matchLabels:
      app: ndn-c
  template:
    metadata:
      labels:
        app: ndn-c
    spec:
      containers:
        - name: ndn-c
          image: harutokobayashi/ndn-fc-workflow-plus:1.0
          tty: true
          stdin: true
      nodeSelector:
        kubernetes.io/hostname: kube3
