apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ndn-b
spec:
  serviceName: "ndn-b-service"
  replicas: 1
  selector:
    matchLabels:
      app: ndn-b
  template:
    metadata:
      labels:
        app: ndn-b
    spec:
      containers:
        - name: ndn-b
          image: harutokobayashi/ndn-fc-workflow-plus:1.0
          tty: true
          stdin: true
      nodeSelector:
        kubernetes.io/hostname: kube2
